[package]
name = "machin"
version = "0.1.0"
authors = ["Ferry Jérémie <ferryjeremie@free.fr>"]
description = "Machin is a cli program that simplifies file conversions and batch processing. It's inspired from filter/map/reduce"
keywords = ["app", "cli", "files", "conversion", "batch"]
categories = ["command-line-utilities"]
license-file = "LICENSE"
readme = "README.md"
edition = "2021"

[dependencies]
clap = { version="3.2", features=['cargo'] }
lopdf="0.20.0"
exitcode="1.1.2"
mime="0.3"
mime_guess="2.0"
resvg="0.14"
usvg="0.14.0"
tiny-skia="0.5"
image= { version="0.24", features=['avif-encoder'] }
markdown = "0.3"
colored = "2"

[build-dependencies]
clap = { version="3.2", features=['cargo'] }
clap_complete = { version="3.2" }
